openapi: 3.0.0
info:
  description: This API will receive orders from grocery stores and restaurants
  version: "1.0.0"
  title: Order taking API
  contact:
    email: karandeepsingh1@my.bcit.ca
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: admins
    description: Operations available to restaurants ands
paths:
  /vanillacake:
    get:
      tags:
       - restaurants
      summary: gets vanilla cake order from history
      operationId: app.get_vanilla_cake_orders
      description: Gets vanilla cake orders added after a timestamp
      parameters:
        - name: index
          in: query
          description: Gets the Vanilla Order at the index in the event store
          schema:
            type: integer
            example: 100
      responses:
        '200':
          description: Successfully returned a vanilla cake event
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/VanillaCake'
        '400':
          description: Invalid request
          content: 
            application/json:
              schema: 
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        
  /chocolatecake:
    get:
      summary: gets chocolate cake order from history
      operationId: app.get_chocolate_cake_orders
      description: Gets chocolate cake order from the event store
      parameters:
        - name: index
          in: query
          description: Gets the chocolate cake order at the index in the event store
          schema:
            type: integer
            example: 100
      responses:
        '200':
          description: Successfully returned a list of chocolate cake order events
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ChocolateCake'
        '400':
          description: Invalid request
          content: 
            application/json:
              schema: 
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Not Found
        
        
components:
  schemas:
    ChocolateCake:
      type: object
      required:
        - cake_id
        - name
        - chocolate_type
        - preparation_method
        - sell_by_date
      properties:
        cake_id:
          type: integer
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: chocolate Orange Cake
        chocolate_type: 
          type: string
          example: milk chocolate
        sell_by_date:
          type: string
          format: date-time
          example: '2016-08-29'
        preparation_method:
          type: string
          example: Creaming
          
    VanillaCake:
      required: 
        - cake_id
        - name
        - vanilla_type
        - preparation_method
        - sell_by_date
        
      properties:
        cake_id: 
          type: integer
          example: d290f1ee-6c54-4b01-90e6-d701748f0852
        name:
          type: string
          example: Vanilla Butter Cake
        vanilla_type: 
          type: string
          example: Thrive market organic vanilla
        sell_by_date:
          type: string
          format: date-time
          example: '2016-08-29'
        preparation_method:
          type: string
          example: all-in-one
      type: object
